version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: ohlc
    ports:
      - "65432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=demo123 pg_isready -U demo -d ohlc"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ohlc:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     POSTGRES_USER: demo
  #     POSTGRES_PASSWORD: demo123
  #     POSTGRES_DB: ohlc
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
    driver: local